export const remindersTypes = {
  GET_REMINDERS: 'GET_REMINDERS',
  ADD_REMINDER: 'ADD_REMINDER',
  TOGGLE_NOTIFICATIONS: 'TOGGLE_NOTIFICATIONS',
  EDIT_REMINDER: 'EDIT_REMINDER',
  REMOVE_REMINDER: 'REMOVE_REMINDER'
}
